version: "3.9"

networks:
  library_net:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: library_app
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV:-production}
    networks:
      - library_net
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: library_tests
    environment:
      APP_ENV: test
    networks:
      - library_net
    volumes:
      - ./coverage.xml:/app/coverage.xml
    profiles:
      - test